# Generated by Django 3.2.4 on 2023-04-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='action_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
