# Generated by Django 4.0 on 2023-08-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='action',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='action_type',
            field=models.CharField(blank=True, max_length=2550, null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='object_id',
            field=models.CharField(max_length=2550),
        ),
    ]
