# Generated by Django 4.0 on 2023-08-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlog', '0002_alter_userlog_action_alter_userlog_action_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='action',
            field=models.CharField(max_length=5000),
        ),
    ]
