# Generated by Django 3.2.4 on 2023-04-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlog', '0002_userlog_action_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='action_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
