# Generated by Django 4.0 on 2023-08-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlog', '0003_alter_userlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='action',
            field=models.TextField(),
        ),
    ]
