# Generated by Django 3.2.4 on 2023-05-04 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userlog', '0004_userlog_invoice_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlog',
            name='invoice_num',
        ),
    ]
