# Generated by Django 3.2.4 on 2024-10-20 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userlog', '0005_remove_userlog_invoice_num'),
    ]

    operations = [
    ]
