# Generated by Django 3.2.4 on 2021-12-12 06:04

from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(blank=True,
                 max_length=255, null=True, unique=True)),
                ('context', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttributeTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(blank=True,
                 max_length=255, null=True, unique=True)),
                ('context', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('Attribute', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='product.attribute')),
            ],
        ),
        migrations.CreateModel(
            name='BulkProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.CharField(blank=True,
                 max_length=255, null=True, unique=True)),
                ('Short_description', models.TextField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
                ('purchase_price', models.IntegerField(blank=True, null=True)),
                ('selling_price', models.IntegerField(
                    blank=True, default=0, null=True)),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('stock_unit', models.CharField(
                    blank=True, max_length=255, null=True)),
                ('stock_alart_amount', models.IntegerField(blank=True, null=True)),
                ('height', models.DecimalField(blank=True,
                 decimal_places=2, max_digits=5, null=True)),
                ('width', models.DecimalField(blank=True,
                 decimal_places=2, max_digits=5, null=True)),
                ('weight', models.DecimalField(blank=True,
                 decimal_places=2, max_digits=5, null=True)),
                ('discount_type', models.CharField(
                    blank=True, max_length=255, null=True)),
                ('discount', models.DecimalField(blank=True,
                 decimal_places=2, max_digits=20, null=True)),
                ('tax', models.DecimalField(blank=True,
                 decimal_places=2, max_digits=20, null=True)),
                ('is_active', models.BooleanField(
                    blank=True, default=True, null=True)),
                ('barcode', models.CharField(blank=True,
                 max_length=255, null=True, unique=True)),
                ('product_code', models.CharField(
                    blank=True, max_length=255, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(blank=True,
                 max_length=255, null=True, unique=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('Category_parent', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.SET_NULL, to='product.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.CharField(blank=True,
                 max_length=255, null=True, unique=True)),
                ('Short_description', models.TextField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
                ('stock_unit', models.CharField(
                    blank=True, max_length=255, null=True)),
                ('stock_alart_amount', models.IntegerField(blank=True, null=True)),
                ('height', models.DecimalField(blank=True,
                 decimal_places=2, max_digits=5, null=True)),
                ('width', models.DecimalField(blank=True,
                 decimal_places=2, max_digits=5, null=True)),
                ('weight', models.DecimalField(blank=True,
                 decimal_places=2, max_digits=5, null=True)),
                ('discount_type', models.CharField(
                    blank=True, max_length=255, null=True)),
                ('discount', models.DecimalField(blank=True,
                 decimal_places=2, max_digits=5, null=True)),
                ('tax', models.DecimalField(blank=True,
                 decimal_places=2, max_digits=5, null=True)),
                ('is_active', models.BooleanField(
                    blank=True, default=True, null=True)),
                ('product_code', models.CharField(
                    blank=True, max_length=255, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='Product_Category', related_query_name='Product_Category', to='product.category')),
                ('Merchandiser', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.SET_NULL, to='contact.contact')),
                ('Sub_Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='Product_Sub_Category', related_query_name='Product_Sub_Category', to='product.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_type', models.CharField(choices=[
                 ('S', 'Single'), ('B', 'Bulk')], default='S', max_length=2)),
                ('quantity', models.IntegerField()),
                ('purchase_price', models.DecimalField(
                    blank=True, decimal_places=2, default=0, max_digits=20)),
                ('selling_price', models.DecimalField(
                    blank=True, decimal_places=2, default=0, max_digits=20)),
                ('price', models.DecimalField(blank=True,
                 decimal_places=2, default=0, max_digits=20)),
                ('barcode', models.CharField(blank=True,
                 max_length=255, null=True, unique=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('BulkProduct', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.CASCADE, to='product.bulkproduct')),
                ('Color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='Color', related_query_name='Color', to='product.attributeterm')),
                ('Custom_one', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='Custom_one', related_query_name='Custom_one', to='product.attributeterm')),
                ('Custom_two', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='Custom_two', related_query_name='Custom_two', to='product.attributeterm')),
                ('ProductDetails', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.CASCADE, to='product.productdetails')),
                ('Size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='Size', related_query_name='Size', to='product.attributeterm')),
            ],
        ),
        migrations.CreateModel(
            name='transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(
                    blank=True, max_length=255, null=True)),
                ('tansfer_number', models.CharField(
                    blank=True, max_length=255, null=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(blank=True, max_length=255)),
                ('deatils', models.CharField(blank=True, max_length=2550)),
                ('data', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True,
                 null=True, upload_to='business/outlet/logo')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('contact', models.CharField(blank=True, max_length=500, null=True)),
                ('petty_cash', models.DecimalField(blank=True,
                 decimal_places=2, default=0, max_digits=20)),
                ('cash', models.DecimalField(blank=True,
                 decimal_places=2, default=0, max_digits=20)),
                ('is_outlet', models.BooleanField(
                    blank=True, default=False, null=True)),
                ('is_office', models.BooleanField(
                    blank=True, default=False, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='transfer_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(
                    blank=True, default='1', null=True)),
                ('is_received', models.BooleanField(
                    blank=True, default=False, null=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.CASCADE, to='product.productlocation')),
                ('transfer', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.CASCADE, to='product.transfer')),
            ],
        ),
        migrations.AddField(
            model_name='transfer',
            name='destance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='destance', related_query_name='destance', to='product.warehouse'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='source', related_query_name='source', to='product.warehouse'),
        ),
        migrations.AddField(
            model_name='productlocation',
            name='Warehouse',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='product.warehouse'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True,
                 upload_to=product.models.product_image_file_path)),
                ('is_active', models.BooleanField(
                    blank=True, default=True, null=True)),
                ('ProductDetails', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.CASCADE, to='product.productdetails')),
                ('ProductLocation', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.CASCADE, to='product.productlocation')),
            ],
        ),
        migrations.CreateModel(
            name='BulkProductList',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, null=True)),
                ('BulkProduct', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='product.bulkproduct')),
                ('ProductDetails', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='product.productdetails')),
            ],
        ),
        migrations.AddField(
            model_name='bulkproduct',
            name='Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='Category', related_query_name='Category', to='product.category'),
        ),
        migrations.AddField(
            model_name='bulkproduct',
            name='Merchandiser',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.contact'),
        ),
        migrations.AddField(
            model_name='bulkproduct',
            name='Sub_Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='Sub_Category', related_query_name='Sub_Category', to='product.category'),
        ),
    ]
