# Generated by Django 4.0 on 2023-08-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlocation',
            name='Attributes',
            field=models.ManyToManyField(blank=True, related_name='Attributes', related_query_name='Attributes', to='product.AttributeTerm'),
        ),
    ]
