# Generated by Django 4.0 on 2024-01-17 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productlocation_attributes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodePrintList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challan_number', models.CharField(blank=True, max_length=255, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('product_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productlocation')),
            ],
        ),
    ]
