# Generated by Django 4.0 on 2024-01-31 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productlocationentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlocationentry',
            name='ProductLocation',
        ),
        migrations.AddField(
            model_name='productlocationentry',
            name='ProductLocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productlocation'),
        ),
    ]
