# Generated by Django 3.2.4 on 2021-12-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20211212_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlocation',
            name='barcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
