# Generated by Django 4.0 on 2024-01-17 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_barcodeprintlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcodeprintlist',
            name='product_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProductLocation', to='product.productlocation'),
        ),
    ]
