# Generated by Django 3.2.4 on 2021-12-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_productlocation_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='max_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
