# Generated by Django 4.0 on 2024-01-17 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_barcodeprintlist_product_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcodeprintlist',
            name='product_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='barcode_print_list', to='product.productlocation'),
        ),
    ]
