# Generated by Django 4.0 on 2024-01-17 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_barcodeprintlist_product_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barcodeprintlist',
            name='product_location',
        ),
        migrations.AddField(
            model_name='barcodeprintlist',
            name='product_locations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProductLocation', to='product.productlocation'),
        ),
    ]
