# Generated by Django 3.2.4 on 2022-01-12 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_productdetails_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='Color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.attributeterm'),
        ),
    ]
