# Generated by Django 4.0 on 2024-01-17 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_barcodeprintlist_product_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barcodeprintlist',
            old_name='quantity',
            new_name='list_quantity',
        ),
    ]
