# Generated by Django 4.0 on 2024-01-31 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_productlocationentry_productlocation_and_more'),
        ('product', '0007_rename_quantity_barcodeprintlist_list_quantity'),
    ]

    operations = [
    ]
