# Generated by Django 3.2.8 on 2022-01-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_productimage_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlocation',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
