# Generated by Django 4.0 on 2024-01-31 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_merge_20240131_1346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barcodeprintlist',
            options={'verbose_name': 'Barcode Print List', 'verbose_name_plural': 'Barcode Print Lists'},
        ),
        migrations.AddField(
            model_name='productlocationentry',
            name='reamrks',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
