# Generated by Django 3.2.4 on 2022-11-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_productlocation_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributeterm',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='attribute_list',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='long_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
