# Generated by Django 4.0 on 2024-01-31 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_barcodeprintlist_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productlocationentry',
            old_name='reamrks',
            new_name='remarks',
        ),
    ]
