# Generated by Django 3.2.4 on 2022-11-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20221121_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='breadcrumbs',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
