# Generated by Django 4.0 on 2024-04-03 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_rename_reamrks_productlocationentry_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductHoldList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Location', to='product.productlocation')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Location', to='product.warehouse')),
            ],
        ),
    ]
