# Generated by Django 3.2.4 on 2023-01-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_productdetails_breadcrumbs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributeterm',
            name='url',
            field=models.TextField(blank=True, default='#', null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.TextField(blank=True, default='#', null=True),
        ),
    ]
