# Generated by Django 4.0 on 2024-05-09 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_productholdlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductHoldList',
        ),
    ]
