# Generated by Django 3.2.4 on 2023-01-31 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20230101_1351'),
        ('product', '0011_auto_20230124_1220'),
    ]

    operations = [
    ]
