# Generated by Django 4.0 on 2024-05-20 09:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_delete_productholdlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='productlocation',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
