# Generated by Django 3.2.4 on 2023-03-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_merge_0011_auto_20230101_1351_0011_auto_20230124_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('url', models.TextField(blank=True, default='#', null=True)),
                ('data', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='productdetails',
            name='is_sellable',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='Tag',
            field=models.ManyToManyField(blank=True, related_name='Tag', related_query_name='Tag', to='product.Tag'),
        ),
    ]
