# Generated by Django 3.2.4 on 2023-03-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20230305_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='online_visible',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='online_visible',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
