# Generated by Django 4.0 on 2024-07-16 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_productdetails_created_productlocation_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='product_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='product_discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='product_discount_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
