# Generated by Django 4.0 on 2024-08-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_productdetails_product_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer_item',
            name='is_returned',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
