# Generated by Django 3.2.4 on 2023-05-24 06:40

from django.db import migrations
import image_optimizer.fields
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_productdetails_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=image_optimizer.fields.OptimizedImageField(blank=True, null=True, upload_to=product.models.product_image_file_path),
        ),
    ]
