# Generated by Django 3.2.4 on 2023-05-24 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_productimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='image',
            new_name='thumbnail',
        ),
    ]
