# Generated by Django 3.2.4 on 2023-08-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_rename_image_productimage_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributeterm',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attributeterm',
            name='meta_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
