# Generated by Django 3.2.4 on 2023-08-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_auto_20230829_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributeterm',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='attributeterm',
            name='meta_title',
        ),
        migrations.AddField(
            model_name='tag',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='meta_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
