# Generated by Django 3.2.4 on 2023-08-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_auto_20230829_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='page_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='page_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
