# Generated by Django 3.2.4 on 2024-02-13 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_productlocation_discounted_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='is_live',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='live_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
