# Generated by Django 3.2.4 on 2024-08-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_auto_20240213_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer_item',
            name='is_returned',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
