# Generated by Django 3.2.4 on 2024-09-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_transfer_item_is_returned'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='business/outlet/logo')),
                ('url', models.TextField(blank=True, default='#', null=True)),
                ('online_visible', models.BooleanField(blank=True, default=False, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
