# Generated by Django 3.2.4 on 2024-09-30 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='data',
        ),
    ]
