# Generated by Django 3.2.4 on 2024-09-30 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_remove_brand_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='Brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Brand', related_query_name='Brand', to='product.brand'),
        ),
    ]
