# Generated by Django 3.2.4 on 2023-10-04 08:24

from django.db import migrations
import image_optimizer.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='thumbnail',
            field=image_optimizer.fields.OptimizedImageField(blank=True, null=True, upload_to='ecommerce'),
        ),
    ]
