# Generated by Django 3.2.4 on 2023-10-05 06:50

from django.db import migrations, models
import image_optimizer.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_image_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ecommerce', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='thumbnail',
            field=image_optimizer.fields.OptimizedImageField(blank=True, null=True, upload_to='ecommerce', verbose_name='thumbnail'),
        ),
    ]
