# Generated by Django 3.2.4 on 2023-10-07 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_auto_20231007_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='page',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.page'),
        ),
        migrations.AlterField(
            model_name='feature_item',
            name='feature',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.feature'),
        ),
    ]
