# Generated by Django 3.2.4 on 2024-02-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_auto_20231007_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_campaign_page',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.TextField(blank=True, null=True),
        ),
    ]
