# Generated by Django 3.2.4 on 2024-06-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_auto_20240228_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
