# Generated by Django 3.2.4 on 2021-12-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='business_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True,
                 null=True, upload_to='business/logo')),
                ('signature', models.ImageField(blank=True,
                 null=True, upload_to='business/signature')),
                ('wordrobe_terms', models.TextField(blank=True, null=True)),
                ('invoice_terms', models.TextField(blank=True, null=True)),
                ('challan_terms', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
