# Generated by Django 3.2.4 on 2023-06-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_settings', '0002_module_sub_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_module',
            name='permission',
            field=models.TextField(blank=True, null=True),
        ),
    ]
