# Generated by Django 3.2.4 on 2024-10-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_settings', '0003_sub_module_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_settings',
            name='address',
            field=models.TextField(blank=True, max_length=2550, null=True),
        ),
        migrations.AlterField(
            model_name='business_settings',
            name='challan_terms',
            field=models.TextField(blank=True, max_length=2550, null=True),
        ),
        migrations.AlterField(
            model_name='business_settings',
            name='invoice_terms',
            field=models.TextField(blank=True, max_length=2550, null=True),
        ),
        migrations.AlterField(
            model_name='business_settings',
            name='wordrobe_terms',
            field=models.TextField(blank=True, max_length=2550, null=True),
        ),
    ]
