# Generated by Django 3.2.4 on 2024-10-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_settings', '0004_auto_20241020_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_settings',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='business_settings',
            name='challan_terms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='business_settings',
            name='invoice_terms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='business_settings',
            name='wordrobe_terms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
