# Generated by Django 3.2.4 on 2021-12-12 06:04

import contact.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(
                    max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(
                    blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False,
                 help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactType',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='userRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('department', models.ForeignKey(blank=True, default=None, null=True,
                 on_delete=django.db.models.deletion.CASCADE, to='contact.department')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True,
                 null=True, upload_to='employee/photo')),
                ('phone', models.CharField(blank=True,
                 max_length=255, null=True, unique=True)),
                ('emergency_phone', models.CharField(
                    blank=True, max_length=255, null=True, unique=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('defaultShift', models.CharField(default='day', max_length=255)),
                ('defaultEntryTime', models.TimeField(blank=True, null=True)),
                ('defaultExitTime', models.TimeField(blank=True, null=True)),
                ('created', models.DateTimeField(
                    default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(
                    default=django.utils.timezone.now)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                 related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True,
                 upload_to=contact.models.user_files_directory_path)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(
                    default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(
                    default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='employee_document', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('emergency_contact', models.CharField(
                    blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('Type', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.CharField(blank=True, max_length=550, null=True)),
                ('account_balance', models.CharField(
                    blank=True, max_length=550, null=True)),
                ('points', models.CharField(blank=True, max_length=550, null=True)),
                ('Special_Date_Type', models.CharField(
                    blank=True, max_length=255, null=True)),
                ('special_dates', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(
                    blank=True, default=True, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('role', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.SET_NULL, to='contact.contacttype')),
            ],
        ),
    ]
