# Generated by Django 4.1.10 on 2023-08-06 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_initial'),
    ]

    operations = [
    ]
