# Generated by Django 3.2.4 on 2021-12-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_employeeprofile_emergency_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='account_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
