# Generated by Django 4.0 on 2023-12-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_userprofile_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacttype',
            name='cupon_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
