# Generated by Django 3.2.8 on 2022-01-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_contact_account_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='defaultEntryTime',
            field=models.TimeField(blank=True, default='10:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='defaultExitTime',
            field=models.TimeField(blank=True, default='20:00:00', null=True),
        ),
    ]
