# Generated by Django 3.2.4 on 2022-04-03 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('software_settings', '0002_module_sub_module'),
        ('contact', '0005_auto_20220116_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='role_permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_create', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('is_update', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('module', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='software_settings.module')),
                ('sub_module', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='software_settings.sub_module')),
                ('user_role', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.userrole')),
            ],
        ),
    ]
