# Generated by Django 3.2.4 on 2023-03-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_role_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='ecommerce_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
