# Generated by Django 3.2.4 on 2023-05-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_contact_ecommerce_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='joining_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='resignation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
