# Generated by Django 3.2.4 on 2023-06-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_contact_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='role_permission',
            name='is_location',
            field=models.BooleanField(default=False),
        ),
    ]
