# Generated by Django 3.2.4 on 2023-06-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_rename_image_productimage_thumbnail'),
        ('contact', '0010_role_permission_is_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='branch',
            field=models.ManyToManyField(blank=True, related_name='branch', related_query_name='branch', to='product.Warehouse'),
        ),
    ]
