# Generated by Django 3.2.4 on 2023-10-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0011_employeeprofile_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
