# Generated by Django 3.2.4 on 2021-12-12 06:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('Typename', models.CharField(max_length=255)),
                ('initialDays', models.IntegerField(
                    blank=True, default=0, null=True)),
                ('created', models.DateTimeField(
                    default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(
                    default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('loanAmount', models.FloatField(
                    blank=True, default=0.0, null=True)),
                ('loanType', models.CharField(blank=True, max_length=255, null=True)),
                ('loanPayableMonths', models.IntegerField(
                    blank=True, default=0, null=True)),
                ('loanPayableAmount', models.FloatField(
                    blank=True, default=0.0, null=True)),
                ('loanStatus', models.CharField(default='pending', max_length=255)),
                ('loanPaymentStatus', models.CharField(
                    default='ongoing', max_length=255)),
                ('note', models.CharField(blank=True,
                 default='', max_length=255, null=True)),
                ('created', models.DateTimeField(
                    default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(
                    default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='employee_loan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('paidAmount', models.FloatField(
                    blank=True, default=0.0, null=True)),
                ('salaryMonth', models.IntegerField(
                    blank=True, default=0, null=True)),
                ('salaryYear', models.IntegerField(
                    blank=True, default=0, null=True)),
                ('paymentDate', models.DateTimeField(
                    default=django.utils.timezone.now)),
                ('created', models.DateTimeField(
                    default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(
                    default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='employee_salary_payment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('monthlySalary', models.FloatField(
                    blank=True, default=0.0, null=True)),
                ('dailyAllowance', models.FloatField(
                    blank=True, default=0.0, null=True)),
                ('incentive', models.FloatField(blank=True, default=0.0, null=True)),
                ('created', models.DateTimeField(
                    default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(
                    default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='employee_salary', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaySlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('salaryMonth', models.IntegerField(
                    blank=True, default=0, null=True)),
                ('salaryYear', models.IntegerField(
                    blank=True, default=0, null=True)),
                ('publicHoliday', models.IntegerField(
                    blank=True, default=0, null=True)),
                ('leave', models.IntegerField(blank=True, default=0, null=True)),
                ('present', models.IntegerField(blank=True, default=0, null=True)),
                ('absent', models.IntegerField(blank=True, default=0, null=True)),
                ('late', models.IntegerField(blank=True, default=0, null=True)),
                ('dayOverTime', models.IntegerField(
                    blank=True, default=0, null=True)),
                ('nightOverTime', models.IntegerField(
                    blank=True, default=0, null=True)),
                ('overtimeTotal', models.FloatField(
                    blank=True, default=0.0, null=True)),
                ('incentiveTotal', models.FloatField(
                    blank=True, default=0.0, null=True)),
                ('dailyAllowanceTotal', models.FloatField(
                    blank=True, default=0.0, null=True)),
                ('fine', models.FloatField(blank=True, default=0.0, null=True)),
                ('loan_adjustment', models.FloatField(
                    blank=True, default=0.0, null=True)),
                ('advance_adjustment', models.FloatField(
                    blank=True, default=0.0, null=True)),
                ('net_salary', models.FloatField(
                    blank=True, default=0.0, null=True)),
                ('amount_1', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_method_info_1', models.CharField(
                    blank=True, max_length=255, null=True)),
                ('amount_2', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_method_info_2', models.CharField(
                    blank=True, max_length=255, null=True)),
                ('paymentDate', models.DateTimeField(
                    default=django.utils.timezone.now)),
                ('created', models.DateTimeField(
                    default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(
                    default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='employee_payslip', to=settings.AUTH_USER_MODEL)),
                ('payment_method_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='employee_payment_account1', to='accounting.account')),
                ('payment_method_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='employee_payment_account2', to='accounting.account')),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='payslip_salary', to='hrm.salary')),
            ],
        ),
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('paidAmount', models.FloatField(
                    blank=True, default=0.0, null=True)),
                ('paymentDate', models.DateTimeField(
                    default=django.utils.timezone.now)),
                ('created', models.DateTimeField(
                    default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(
                    default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='employee_loan_payment', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='loan_payment_loan', to='hrm.loan')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('leaveStart', models.DateField(default=django.utils.timezone.now)),
                ('leaveEnd', models.DateField(default=django.utils.timezone.now)),
                ('leaveDays', models.IntegerField(
                    blank=True, default=0, null=True)),
                ('leaveStatus', models.CharField(
                    default='pending', max_length=255)),
                ('note', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(
                    default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(
                    default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='employee_leave', to=settings.AUTH_USER_MODEL)),
                ('leaveType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='employee_leave_type', to='hrm.leavetype')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('attendanceDate', models.DateField(default=datetime.date.today)),
                ('shift', models.CharField(default='day', max_length=255)),
                ('isAttended', models.BooleanField(default=False)),
                ('entryTime', models.TimeField(blank=True, null=True)),
                ('exitTime', models.TimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True,
                 default='', max_length=255, null=True)),
                ('overTime', models.FloatField(blank=True, default=0.0, null=True)),
                ('lateTime', models.FloatField(blank=True, default=0.0, null=True)),
                ('created', models.DateTimeField(
                    default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(
                    default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='employee_attendance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
