# Generated by Django 3.2.4 on 2021-12-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='amount_1',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='amount_2',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
