# Generated by Django 4.0 on 2023-08-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='Department',
            field=models.ManyToManyField(blank=True, to='hrm.Department'),
        ),
    ]
