# Generated by Django 3.2.8 on 2022-01-15 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_journal_loan'),
        ('hrm', '0003_auto_20211225_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_payment_method', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loanPaymentStatus',
            field=models.CharField(default='pending', max_length=255),
        ),
    ]
