# Generated by Django 3.2.8 on 2022-01-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0004_auto_20220115_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='isLate',
            field=models.BooleanField(default=False),
        ),
    ]
