# Generated by Django 3.2.4 on 2023-04-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0005_attendance_islate'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='bonusamount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='bonuspercent',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
