# Generated by Django 4.0 on 2023-08-08 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0005_alter_payslip_payment_method_info_1_and_more'),
    ]

    operations = [
    ]
