# Generated by Django 4.0 on 2023-08-08 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0006_auto_20230808_2017'),
    ]

    operations = [
    ]
