# Generated by Django 3.2.4 on 2023-09-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0007_payslip_manual_adjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='manual_adjustment_reference',
            field=models.TextField(blank=True, null=True),
        ),
    ]
