# Generated by Django 4.0 on 2023-08-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0007_auto_20230808_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='payment_method_info_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='payment_method_info_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
