# Generated by Django 3.2.4 on 2023-09-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0008_payslip_manual_adjustment_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='OverTime',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='OverTimeHour',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='current_allowance',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='current_loan',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='current_salary',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='current_salary_day',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='current_salary_day_hour',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='current_salary_night',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='current_salary_night_hour',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='dayOverTimeHour',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='nightOverTimeHour',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
