# Generated by Django 3.2.4 on 2023-09-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0009_auto_20230907_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='OverTime',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='OverTimeHour',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='dayOverTime',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='dayOverTimeHour',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='nightOverTime',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='nightOverTimeHour',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
