# Generated by Django 3.2.4 on 2024-08-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0010_auto_20230927_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='OvertimeNightAllowance',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='salary',
            name='mobileAllowance',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
