# Generated by Django 4.0 on 2023-08-09 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_userprofile_groups_and_more'),
        ('hrm', '0010_alter_payslip_payment_method_info_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpayment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_loan_payment', to='contact.userprofile'),
        ),
    ]
