# Generated by Django 3.2.4 on 2024-08-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0011_auto_20240825_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='OvertimeNightAllowance',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='current_OvertimeNightAllowance',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='current_mobileAllowance',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='mobileAllowance',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
