# Generated by Django 4.0 on 2023-08-13 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0011_alter_loanpayment_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpayment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_loan_payment', to='hrm.employee'),
        ),
    ]
