# Generated by Django 4.0 on 2023-08-13 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0012_alter_loanpayment_employee'),
    ]

    operations = [
    ]
