# Generated by Django 4.1.10 on 2023-08-06 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0001_initial'),
    ]

    operations = [
    ]
