# Generated by Django 4.0 on 2023-08-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productlocation_attributes'),
        ('manufacturing', '0002_auto_20230806_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorderitem',
            name='Attributes',
            field=models.ManyToManyField(blank=True, related_name='AttributeTerm', related_query_name='AttributeTerm', to='product.AttributeTerm'),
        ),
    ]
