# Generated by Django 4.0 on 2023-08-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0003_alter_workorderitem_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionline',
            name='capacity_consumed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productionline_item',
            name='quantity_complete',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productionline_item',
            name='quantity_damaged',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productionline_item',
            name='quantity_pending',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workorder',
            name='quantity_complete',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workorder',
            name='quantity_damaged',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workorder',
            name='quantity_pending',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workorderitem',
            name='quantity_complete',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workorderitem',
            name='quantity_damaged',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workorderitem',
            name='quantity_pending',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='quantity_needed',
            field=models.IntegerField(default=0),
        ),
    ]
