# Generated by Django 4.0 on 2023-10-01 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_invoice_payment'),
        ('manufacturing', '0004_productionline_capacity_consumed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.services'),
        ),
    ]
