# Generated by Django 3.2.4 on 2021-12-12 06:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('account_no', models.CharField(
                    blank=True, max_length=255, null=True)),
                ('cash', models.DecimalField(blank=True,
                 decimal_places=2, default=0, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='chartofaccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=255)),
                ('account_code', models.CharField(max_length=255, unique=True)),
                ('Financial_statement', models.TextField(blank=True, null=True)),
                ('normally_Debit', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(blank=True, null=True)),
                ('voucher_type', models.TextField(blank=True, null=True)),
                ('amount', models.IntegerField()),
                ('increase', models.BooleanField(
                    blank=True, default=True, null=True)),
                ('is_checked', models.BooleanField(
                    blank=True, default=False, null=True)),
                ('created', models.DateTimeField(
                    default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(
                    default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='journalvoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(max_length=255)),
                ('amount', models.DecimalField(blank=True,
                 decimal_places=2, default=0, max_digits=20, null=True)),
                ('created', models.DateTimeField(
                    default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(
                    default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='journalvoucheritems',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('narration', models.TextField()),
                ('increase', models.BooleanField(
                    blank=True, default=True, null=True)),
                ('amount', models.DecimalField(blank=True,
                 decimal_places=2, default=0, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='paymentvoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(max_length=255)),
                ('amount', models.DecimalField(blank=True,
                 decimal_places=2, default=0, max_digits=20, null=True)),
                ('created', models.DateTimeField(
                    default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(
                    default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='paymentvoucheritems',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('narration', models.TextField()),
                ('increase', models.BooleanField(
                    blank=True, default=True, null=True)),
                ('amount', models.DecimalField(blank=True,
                 decimal_places=2, default=0, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='pettycash',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('narration', models.CharField(max_length=900)),
                ('amount', models.DecimalField(blank=True,
                 decimal_places=2, default=0, max_digits=20, null=True)),
                ('increase', models.BooleanField(
                    blank=True, default=True, null=True)),
                ('created', models.DateTimeField(
                    default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(
                    default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='receivevoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(max_length=255)),
                ('amount', models.DecimalField(blank=True,
                 decimal_places=2, default=0, max_digits=20, null=True)),
                ('created', models.DateTimeField(
                    default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(
                    default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='receivevoucheritems',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('narration', models.TextField()),
                ('increase', models.BooleanField(
                    blank=True, default=True, null=True)),
                ('amount', models.DecimalField(blank=True,
                 decimal_places=2, default=0, max_digits=20, null=True)),
                ('account', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.SET_NULL, to='accounting.account')),
                ('chartofaccount', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.SET_NULL, to='accounting.chartofaccount')),
            ],
        ),
    ]
