
# Generated by Django 4.1.10 on 2023-08-06 14:36



from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [

        ('order', '0001_initial'),
        ('product', '0001_initial'),
        ('contact', '0001_initial'),
        ('hrm', '0001_initial'),
        ('accounting', '0001_initial'),

        ('contact', '0001_initial'),
        ('hrm', '0001_initial'),
        ('order', '0001_initial'),
        ('accounting', '0001_initial'),
        ('product', '0001_initial'),

    ]

    operations = [
        migrations.AddField(
            model_name='receivevoucheritems',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.contact'),
        ),
        migrations.AddField(
            model_name='receivevoucheritems',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrm.employee'),
        ),
        migrations.AddField(
            model_name='receivevoucheritems',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.invoice'),
        ),
        migrations.AddField(
            model_name='receivevoucheritems',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrm.office'),
        ),
        migrations.AddField(
            model_name='receivevoucheritems',
            name='purchasee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.purchase'),
        ),
        migrations.AddField(
            model_name='receivevoucheritems',
            name='receivevoucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.receivevoucher'),
        ),
        migrations.AddField(
            model_name='receivevoucher',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.account'),
        ),
        migrations.AddField(
            model_name='receivevoucher',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.contact'),
        ),
        migrations.AddField(
            model_name='receivevoucher',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrm.employee'),
        ),
        migrations.AddField(
            model_name='receivevoucher',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.invoice'),
        ),
        migrations.AddField(
            model_name='receivevoucher',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrm.office'),
        ),
        migrations.AddField(
            model_name='receivevoucher',
            name='purchasee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.purchase'),
        ),
        migrations.AddField(
            model_name='pettycash_transfer',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.account'),
        ),
        migrations.AddField(
            model_name='pettycash_transfer',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrm.office'),
        ),
        migrations.AddField(
            model_name='pettycash',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrm.employee'),
        ),
        migrations.AddField(
            model_name='pettycash',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrm.office'),
        ),
        migrations.AddField(
            model_name='paymentvoucheritems',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.account'),
        ),
        migrations.AddField(
            model_name='paymentvoucheritems',
            name='chartofaccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.chartofaccount'),
        ),
        migrations.AddField(
            model_name='paymentvoucheritems',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.contact'),
        ),
        migrations.AddField(
            model_name='paymentvoucheritems',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrm.employee'),
        ),
        migrations.AddField(
            model_name='paymentvoucheritems',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.invoice'),
        ),
        migrations.AddField(
            model_name='paymentvoucheritems',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrm.office'),
        ),
        migrations.AddField(
            model_name='paymentvoucheritems',
            name='paymentvoucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.paymentvoucher'),
        ),
        migrations.AddField(
            model_name='paymentvoucheritems',
            name='purchasee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.purchase'),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.account'),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.contact'),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrm.employee'),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.invoice'),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrm.office'),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='purchasee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.purchase'),
        ),
        migrations.AddField(
            model_name='journalvoucheritems',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.account'),
        ),
        migrations.AddField(
            model_name='journalvoucheritems',
            name='chartofaccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.chartofaccount'),
        ),
        migrations.AddField(
            model_name='journalvoucheritems',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.contact'),
        ),
        migrations.AddField(
            model_name='journalvoucheritems',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrm.employee'),
        ),
        migrations.AddField(
            model_name='journalvoucheritems',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.invoice'),
        ),
        migrations.AddField(
            model_name='journalvoucheritems',
            name='journalvoucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.journalvoucher'),
        ),
        migrations.AddField(
            model_name='journalvoucheritems',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrm.office'),
        ),
        migrations.AddField(
            model_name='journalvoucheritems',
            name='purchasee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.purchase'),
        ),
        migrations.AddField(
            model_name='journalvoucher',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.account'),
        ),
        migrations.AddField(
            model_name='journalvoucher',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.contact'),
        ),
        migrations.AddField(
            model_name='journalvoucher',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrm.employee'),
        ),
        migrations.AddField(
            model_name='journalvoucher',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.invoice'),
        ),
        migrations.AddField(
            model_name='journalvoucher',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrm.office'),
        ),
        migrations.AddField(
            model_name='journalvoucher',
            name='purchasee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.purchase'),
        ),
        migrations.AddField(
            model_name='journal',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.account'),
        ),
        migrations.AddField(
            model_name='journal',
            name='chartofaccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.chartofaccount'),
        ),
        migrations.AddField(
            model_name='journal',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.contact'),
        ),
        migrations.AddField(
            model_name='journal',
            name='employe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrm.employee'),
        ),
        migrations.AddField(
            model_name='journal',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.invoice'),
        ),
        migrations.AddField(
            model_name='journal',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrm.loan'),
        ),
        migrations.AddField(
            model_name='journal',
            name='outlet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrm.office'),
        ),
        migrations.AddField(
            model_name='journal',
            name='payslip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrm.payslip'),
        ),
        migrations.AddField(
            model_name='journal',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productdetails'),
        ),
        migrations.AddField(
            model_name='journal',
            name='purchasee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.purchase'),
        ),
        migrations.AddField(
            model_name='journal',
            name='transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.transfer'),
        ),
        migrations.AddField(
            model_name='contravoucher',
            name='accountFrom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accountFrom', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='contravoucher',
            name='accountTo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accountTo', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='contravoucher',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrm.employee'),
        ),
        migrations.AddField(
            model_name='contravoucher',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrm.office'),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupp', related_query_name='groupp', to='accounting.chartofaccount'),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='sub_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_groupp', related_query_name='sub_groupp', to='accounting.chartofaccount'),
        ),
        migrations.AddField(
            model_name='account',
            name='accountparent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.accountparent'),
        ),
    ]
