# Generated by Django 3.2.4 on 2021-12-12 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contact', '0001_initial'),
        ('product', '0001_initial'),
        ('order', '0001_initial'),
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivevoucheritems',
            name='contact',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.contact'),
        ),
        migrations.AddField(
            model_name='receivevoucheritems',
            name='employee',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receivevoucheritems',
            name='invoice',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.invoice'),
        ),
        migrations.AddField(
            model_name='receivevoucheritems',
            name='location',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.warehouse'),
        ),
        migrations.AddField(
            model_name='receivevoucheritems',
            name='purchasee',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.purchase'),
        ),
        migrations.AddField(
            model_name='receivevoucheritems',
            name='receivevoucher',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='accounting.receivevoucher'),
        ),
        migrations.AddField(
            model_name='receivevoucher',
            name='employee',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receivevoucher',
            name='location',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.warehouse'),
        ),
        migrations.AddField(
            model_name='pettycash',
            name='employee',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pettycash',
            name='location',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.warehouse'),
        ),
        migrations.AddField(
            model_name='paymentvoucheritems',
            name='account',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.account'),
        ),
        migrations.AddField(
            model_name='paymentvoucheritems',
            name='chartofaccount',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.chartofaccount'),
        ),
        migrations.AddField(
            model_name='paymentvoucheritems',
            name='contact',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.contact'),
        ),
        migrations.AddField(
            model_name='paymentvoucheritems',
            name='employee',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentvoucheritems',
            name='invoice',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.invoice'),
        ),
        migrations.AddField(
            model_name='paymentvoucheritems',
            name='location',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.warehouse'),
        ),
        migrations.AddField(
            model_name='paymentvoucheritems',
            name='paymentvoucher',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='accounting.paymentvoucher'),
        ),
        migrations.AddField(
            model_name='paymentvoucheritems',
            name='purchasee',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.purchase'),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='employee',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='location',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.warehouse'),
        ),
        migrations.AddField(
            model_name='journalvoucheritems',
            name='account',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.account'),
        ),
        migrations.AddField(
            model_name='journalvoucheritems',
            name='chartofaccount',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.chartofaccount'),
        ),
        migrations.AddField(
            model_name='journalvoucheritems',
            name='contact',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.contact'),
        ),
        migrations.AddField(
            model_name='journalvoucheritems',
            name='employee',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalvoucheritems',
            name='invoice',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.invoice'),
        ),
        migrations.AddField(
            model_name='journalvoucheritems',
            name='journalvoucher',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='accounting.journalvoucher'),
        ),
        migrations.AddField(
            model_name='journalvoucheritems',
            name='location',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.warehouse'),
        ),
        migrations.AddField(
            model_name='journalvoucheritems',
            name='purchasee',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.purchase'),
        ),
        migrations.AddField(
            model_name='journalvoucher',
            name='employee',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalvoucher',
            name='location',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.warehouse'),
        ),
        migrations.AddField(
            model_name='journal',
            name='account',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.account'),
        ),
        migrations.AddField(
            model_name='journal',
            name='chartofaccount',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='accounting.chartofaccount'),
        ),
        migrations.AddField(
            model_name='journal',
            name='contact',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.contact'),
        ),
        migrations.AddField(
            model_name='journal',
            name='employe',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journal',
            name='invoice',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.invoice'),
        ),
        migrations.AddField(
            model_name='journal',
            name='outlet',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.warehouse'),
        ),
        migrations.AddField(
            model_name='journal',
            name='purchasee',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.purchase'),
        ),
        migrations.AddField(
            model_name='journal',
            name='transfer',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.transfer'),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='groupp', related_query_name='groupp', to='accounting.chartofaccount'),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='sub_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='sub_groupp', related_query_name='sub_groupp', to='accounting.chartofaccount'),
        ),
    ]
