# Generated by Django 3.2.4 on 2021-12-13 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('contact', '0002_initial'),
        ('accounting', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalvoucher',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.account'),
        ),
        migrations.AddField(
            model_name='journalvoucher',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.contact'),
        ),
        migrations.AddField(
            model_name='journalvoucher',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.invoice'),
        ),
        migrations.AddField(
            model_name='journalvoucher',
            name='purchasee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.purchase'),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.account'),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.contact'),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.invoice'),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='purchasee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.purchase'),
        ),
        migrations.AddField(
            model_name='receivevoucher',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.account'),
        ),
        migrations.AddField(
            model_name='receivevoucher',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.contact'),
        ),
        migrations.AddField(
            model_name='receivevoucher',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.invoice'),
        ),
        migrations.AddField(
            model_name='receivevoucher',
            name='purchasee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.purchase'),
        ),
    ]
