# Generated by Django 3.2.4 on 2021-12-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_auto_20211213_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalvoucher',
            name='narration',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalvoucher',
            name='referance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='narration',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='referance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receivevoucher',
            name='narration',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receivevoucher',
            name='referance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journalvoucheritems',
            name='narration',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentvoucheritems',
            name='narration',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receivevoucheritems',
            name='narration',
            field=models.TextField(blank=True, null=True),
        ),
    ]
