# Generated by Django 3.2.4 on 2021-12-18 11:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_auto_20211216_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalvoucheritems',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='journalvoucheritems',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='paymentvoucheritems',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='paymentvoucheritems',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='receivevoucheritems',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='receivevoucheritems',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
