# Generated by Django 3.2.4 on 2021-12-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_contravoucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='txnCharge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
