# Generated by Django 3.2.4 on 2021-12-25 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0003_auto_20211225_0824'),
        ('accounting', '0009_alter_journal_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='payslip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrm.payslip'),
        ),
    ]
