# Generated by Django 3.2.4 on 2021-12-26 09:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20211219_1512'),
        ('accounting', '0010_journal_payslip'),
    ]

    operations = [
        migrations.CreateModel(
            name='pettycash_transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('pett_cash_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('collect_cash', models.BooleanField(blank=True, default=False, null=True)),
                ('add_cash', models.BooleanField(blank=True, default=False, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.account')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.warehouse')),
            ],
        ),
    ]
