# Generated by Django 3.2.4 on 2021-12-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_journal_payslip'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalvoucher',
            name='credit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='journalvoucher',
            name='debit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
