# Generated by Django 3.2.4 on 2021-12-27 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_auto_20211226_0224'),
        ('accounting', '0011_pettycash_transfer'),
    ]

    operations = [
    ]
