# Generated by Django 3.2.4 on 2022-01-03 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20211219_1512'),
        ('accounting', '0012_merge_0011_auto_20211226_0224_0011_pettycash_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productlocation'),
        ),
    ]
