# Generated by Django 3.2.4 on 2022-01-03 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20211219_1512'),
        ('accounting', '0013_journal_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productdetails'),
        ),
    ]
