# Generated by Django 3.2.4 on 2022-01-04 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_alter_journal_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
