# Generated by Django 3.2.4 on 2022-01-04 23:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_auto_20220105_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='journal',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
