# Generated by Django 3.2.8 on 2022-01-15 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0003_auto_20211225_0824'),
        ('accounting', '0016_auto_20220105_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrm.loan'),
        ),
    ]
