# Generated by Django 3.2.4 on 2023-02-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_journal_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartofaccount',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
