# Generated by Django 3.2.4 on 2023-02-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0018_auto_20230218_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
