# Generated by Django 3.2.4 on 2023-05-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0021_accountstatus_accountstatusbydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountstatusbydate',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
