# Generated by Django 3.2.4 on 2023-05-24 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0022_accountstatusbydate_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountstatusbydate',
            name='accountStatus',
        ),
    ]
