# Generated by Django 3.2.4 on 2023-12-31 06:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0023_remove_accountstatusbydate_accountstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pettycash',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
