

from django.db import migrations, models
import django.db.models.deletion
import order.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0001_initial'),
        ('product', '0001_initial'),
        ('accounting', '0001_initial'),
        ('hrm', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('limit_type', models.CharField(blank=True, default='unlimited', max_length=255, null=True)),
                ('limit', models.IntegerField(default=0)),
                ('ref_type', models.CharField(choices=[('P', 'Percentage'), ('A', 'Amount')], default='A', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DraftCostSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_name', models.CharField(max_length=100)),
                ('client_name', models.CharField(max_length=100)),
                ('style_code', models.CharField(max_length=100)),
                ('designer_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('net_total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('profit_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('net_selling_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('data', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=255)),
                ('order_number', models.CharField(blank=True, max_length=255)),
                ('shipping_address', models.TextField(blank=True)),
                ('delivery_charge', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('delivery_cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('delivery_person', models.CharField(blank=True, max_length=255)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('program_date', models.DateField(blank=True, null=True)),
                ('Payment_method', models.CharField(blank=True, max_length=255, null=True)),
                ('Account_no', models.CharField(blank=True, max_length=255)),
                ('Transection_no', models.CharField(blank=True, max_length=255)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('bill', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('due', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('discountlimit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('costing', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('profit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('payment', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('advance_payment', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('is_delivered', models.BooleanField(default=False)),
                ('data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('Vat_issued_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='Pending', max_length=255, null=True)),
                ('address1', models.TextField(blank=True, null=True)),
                ('address2', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.CharField(blank=True, max_length=255, null=True)),
                ('postalCode', models.CharField(blank=True, max_length=255, null=True)),
                ('thana', models.CharField(blank=True, max_length=255, null=True)),
                ('s_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('shipping_method', models.CharField(blank=True, max_length=255, null=True)),
                ('DeliveryType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.deliverytype')),
                ('Sales_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Sales_person', related_query_name='Sales_person', to='hrm.employee')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.account')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.contact')),
                ('cupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.cupon')),
                ('employe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employe', related_query_name='employe', to='hrm.employee')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrm.office')),
            ],
        ),
        migrations.CreateModel(
            name='purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_number', models.CharField(blank=True, max_length=255, null=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_method', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('Payment_method', models.CharField(blank=True, max_length=255, null=True)),
                ('Account_no', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('bill', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('due', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('costing', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('shipping', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('payment', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('adjustment', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('is_received', models.BooleanField(default=False)),
                ('received_item', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('received_item_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('tax_type', models.CharField(blank=True, default='Pending', max_length=255, null=True)),
                ('status', models.CharField(blank=True, default='Pending', max_length=255, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.account')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.contact')),
                ('employe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrm.employee')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrm.office')),
            ],
        ),
        migrations.CreateModel(
            name='refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, max_length=255)),
                ('deatils', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('quantity', models.IntegerField(blank=True, default=0)),
                ('profit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('employe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrm.employee')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.invoice')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productlocation')),
            ],
        ),
        migrations.CreateModel(
            name='wordrobe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wordrobe_number', models.CharField(blank=True, max_length=255, null=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('registered_Address', models.TextField(blank=True, null=True)),
                ('company_profile_link', models.TextField(blank=True, null=True)),
                ('photographer_name', models.TextField(blank=True, null=True)),
                ('model_name', models.TextField(blank=True, null=True)),
                ('makeup_artist_name', models.TextField(blank=True, null=True)),
                ('delivery_method', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('Payment_method', models.CharField(blank=True, max_length=255, null=True)),
                ('Account_no', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('product_cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('rent', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('payment', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('due', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(blank=True, default='Pending', max_length=255, null=True)),
                ('is_returned', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.contact')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrm.office')),
            ],
        ),
        migrations.CreateModel(
            name='wordrobe_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Details', models.CharField(blank=True, max_length=2000, null=True)),
                ('quantity', models.IntegerField(blank=True, default='1', null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('is_returned', models.BooleanField(default=False)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productlocation')),
                ('wordrobe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.wordrobe')),
            ],
        ),
        migrations.CreateModel(
            name='services_costing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(blank=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('quantity', models.IntegerField(blank=True, default=1)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productlocation')),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.services')),
            ],
        ),
        migrations.CreateModel(
            name='purchase_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Details', models.CharField(blank=True, max_length=2000, null=True)),
                ('quantity', models.IntegerField(blank=True, default='1', null=True)),
                ('damage', models.IntegerField(blank=True, null=True)),
                ('received', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('landing_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productlocation')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.purchase')),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='refund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.refund'),
        ),
        migrations.CreateModel(
            name='measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blouse', models.BooleanField(default=False)),
                ('Kameez', models.BooleanField(default=False)),
                ('Gown', models.BooleanField(default=False)),
                ('Skirt', models.BooleanField(default=False)),
                ('Paladzo', models.BooleanField(default=False)),
                ('Pant', models.BooleanField(default=False)),
                ('Gharara', models.BooleanField(default=False)),
                ('Note', models.TextField(blank=True)),
                ('Chest', models.CharField(blank=True, max_length=255)),
                ('Waist', models.CharField(blank=True, max_length=255)),
                ('Hand_opening', models.CharField(blank=True, max_length=255)),
                ('Hip', models.CharField(blank=True, max_length=255)),
                ('Length', models.CharField(blank=True, max_length=255)),
                ('End', models.CharField(blank=True, max_length=255)),
                ('Slit', models.CharField(blank=True, max_length=255)),
                ('Shoulder', models.CharField(blank=True, max_length=255)),
                ('Neck_deep_f', models.CharField(blank=True, max_length=255)),
                ('Arm_hole', models.CharField(blank=True, max_length=255)),
                ('Neck_deep_b', models.CharField(blank=True, max_length=255)),
                ('Sleeve_l', models.CharField(blank=True, max_length=255)),
                ('Half_body', models.CharField(blank=True, max_length=255)),
                ('Muscle', models.CharField(blank=True, max_length=255)),
                ('Length_bottom', models.CharField(blank=True, max_length=255)),
                ('Waist_bottom', models.CharField(blank=True, max_length=255)),
                ('Hip_bottom', models.CharField(blank=True, max_length=255)),
                ('Thigh', models.CharField(blank=True, max_length=255)),
                ('Knee', models.CharField(blank=True, max_length=255)),
                ('Leg_openning', models.CharField(blank=True, max_length=255)),
                ('data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('is_basic', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.contact')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.invoice')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productlocation')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.services')),
            ],
        ),
        migrations.CreateModel(
            name='invoice_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Details', models.CharField(blank=True, max_length=2000, null=True)),
                ('quantity', models.IntegerField(default='1')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.invoice')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productlocation')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='refund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.refund'),
        ),
        migrations.CreateModel(
            name='exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default='1', null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('reason', models.CharField(max_length=255)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(blank=True, max_length=255)),
                ('deatils', models.CharField(blank=True, max_length=2550)),
                ('Exchange_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productlocation')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.invoice')),
                ('services', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.services')),
            ],
        ),
        migrations.CreateModel(
            name='DraftOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_sheet_items', models.CharField(choices=[('Fabrics', 'Fabrics'), ('Trims/Accessories', 'Trims/Accessories'), ('Labor Cost', 'Labor Cost')], max_length=100, null=True)),
                ('draft_name', models.CharField(blank=True, max_length=255, null=True)),
                ('unit_quantity', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('unit_name', models.CharField(choices=[('Yards', 'Yards'), ('Pcs', 'Pcs'), ('Hours', 'Hours')], max_length=100, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('cost_sheet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.draftcostsheet')),
            ],
        ),
        migrations.CreateModel(
            name='DraftImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(null=True, upload_to=order.models.draft_image_file_path)),
                ('cost_sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.draftcostsheet')),
            ],
        ),
    ]
