# Generated by Django 4.0 on 2023-08-13 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
    ]
