# Generated by Django 3.2.4 on 2021-12-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_invoice_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
