# Generated by Django 4.0 on 2023-09-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20230813_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
