# Generated by Django 4.0 on 2023-09-30 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0013_auto_20230813_1349'),
        ('accounting', '0002_initial'),
        ('order', '0003_invoice_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='invoice_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('bill', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('due', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('payment', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('advance_payment', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('Sales_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrm.employee')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.account')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.invoice')),
            ],
        ),
    ]
