# Generated by Django 3.2.4 on 2021-12-16 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20211212_1835'),
        ('order', '0003_purchase_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordrobe_item',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productlocation'),
        ),
    ]
