# Generated by Django 4.0 on 2023-12-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_invoice_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='refund',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
