# Generated by Django 3.2.4 on 2021-12-23 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0009_alter_journal_amount'),
        ('order', '0004_alter_wordrobe_item_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.account'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='employe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
