# Generated by Django 4.0 on 2023-12-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_invoice_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_payment',
            name='refund',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
