# Generated by Django 3.2.4 on 2022-01-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_wordrobe_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_item',
            name='landing_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
