# Generated by Django 3.2.4 on 2022-01-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_purchase_item_landing_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discountlimit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20),
        ),
    ]
