# Generated by Django 4.0 on 2024-04-16 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_invoice_receive_invoice_payment_receive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_payment',
            name='issue_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
