# Generated by Django 3.2.4 on 2022-02-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_invoice_discountlimit'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='adjustment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20),
        ),
    ]
