# Generated by Django 4.0 on 2024-04-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_invoice_payment_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(blank=True, default='Paid', max_length=255, null=True),
        ),
    ]
