# Generated by Django 3.2.4 on 2022-02-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_purchase_adjustment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services_costing',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20),
        ),
    ]
