# Generated by Django 3.2.4 on 2022-02-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_invoice_vat_issued_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='received_item',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='purchase',
            name='received_item_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20),
        ),
    ]
