# Generated by Django 4.0 on 2025-01-11 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_transfer_item_is_returned'),
        ('order', '0011_invoice_additional_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='invoice_item_copy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Details', models.CharField(blank=True, max_length=2000, null=True)),
                ('quantity', models.IntegerField(default='1')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('data', models.JSONField(blank=True, null=True)),
                ('is_exchanged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.invoice')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productlocation')),
            ],
        ),
    ]
