# Generated by Django 3.2.4 on 2023-01-01 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0012_auto_20220227_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='Sales_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Sales_person', related_query_name='Sales_person', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='employe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employe', related_query_name='employe', to=settings.AUTH_USER_MODEL),
        ),
    ]
