# Generated by Django 3.2.4 on 2023-02-02 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20230101_1351'),
        ('contact', '0006_role_permission'),
        ('order', '0013_auto_20230101_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.contact'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productlocation'),
        ),
    ]
