# Generated by Django 3.2.4 on 2023-02-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_auto_20230202_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
