# Generated by Django 3.2.4 on 2023-03-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_alter_invoice_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='is_basic',
            field=models.BooleanField(default=False),
        ),
    ]
