# Generated by Django 3.2.4 on 2023-03-03 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_measurement_is_basic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.invoice'),
        ),
    ]
