# Generated by Django 3.2.4 on 2023-03-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_auto_20230308_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='s_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
