# Generated by Django 3.2.4 on 2023-03-13 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20230305_1350'),
        ('order', '0020_invoice_s_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productlocation'),
        ),
    ]
