# Generated by Django 3.2.4 on 2023-03-20 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_services_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.services'),
        ),
    ]
