# Generated by Django 3.2.4 on 2023-06-20 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_auto_20230620_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='shipping_address',
        ),
    ]
