# Generated by Django 3.2.4 on 2023-06-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_remove_invoice_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='shipping_address',
            field=models.TextField(blank=True),
        ),
    ]
