# Generated by Django 3.2.4 on 2023-06-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_invoice_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='Sleeve_length',
            field=models.BooleanField(default=False),
        ),
    ]
