# Generated by Django 3.2.4 on 2023-06-22 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_measurement_sleeve_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='Measurement_body',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='Measurement_dress',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='Sleeve_length',
        ),
    ]
