# Generated by Django 3.2.4 on 2023-06-25 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0027_auto_20230622_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='Type',
            field=models.CharField(blank=True, choices=[('body', 'body'), ('dress', 'dress')], max_length=250, null=True),
        ),
    ]
