# Generated by Django 3.2.4 on 2023-09-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0028_measurement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='Gown_bottom',
            field=models.BooleanField(default=False),
        ),
    ]
