# Generated by Django 3.2.4 on 2023-12-31 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0030_invoice_is_sms_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='realter',
            field=models.BooleanField(default=False),
        ),
    ]
