# Generated by Django 3.2.4 on 2024-01-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0031_services_realter'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='Received_by_factory_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='delivered_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
