# Generated by Django 3.2.4 on 2024-01-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0032_auto_20240110_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tran_id', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('tran_date', models.DateTimeField(blank=True, null=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
