# Generated by Django 3.2.4 on 2024-01-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0033_ipn'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipn',
            name='card_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
