# Generated by Django 3.2.4 on 2024-02-20 07:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0024_alter_pettycash_created'),
        ('product', '0022_auto_20240213_1129'),
        ('order', '0034_ipn_card_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='refund',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='refund',
        ),
        migrations.AddField(
            model_name='refund',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='in_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_account', related_query_name='in_account', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='refund',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.invoice'),
        ),
        migrations.AddField(
            model_name='refund',
            name='issue_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='refund',
            name='out_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='out_account', related_query_name='out_account', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='deatils',
            field=models.CharField(blank=True, max_length=2550),
        ),
        migrations.CreateModel(
            name='Refund_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default='1', null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('reason', models.CharField(max_length=255)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(blank=True, max_length=255)),
                ('deatils', models.CharField(blank=True, max_length=2550)),
                ('Refunded_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productlocation')),
            ],
        ),
    ]
