# Generated by Django 3.2.4 on 2024-03-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0035_auto_20240220_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_refunded',
            field=models.BooleanField(default=False),
        ),
    ]
