# Generated by Django 3.2.4 on 2024-04-24 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0036_invoice_is_refunded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.invoice'),
        ),
    ]
