# Generated by Django 3.2.4 on 2024-07-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0038_online_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='online_order',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
