# Generated by Django 3.2.4 on 2024-09-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0039_online_order_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_mute',
            field=models.BooleanField(default=True),
        ),
    ]
