# Generated by Django 3.2.4 on 2024-10-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0040_invoice_is_mute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
