# Generated by Django 3.2.4 on 2024-10-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0041_alter_refund_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='deatils',
        ),
        migrations.AddField(
            model_name='refund',
            name='reference',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
