# Generated by Django 3.2.4 on 2024-12-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0042_auto_20241026_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='body',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='measurement',
            name='mala',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='measurement',
            name='pagri',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
